name: openrouter
description: Configuration for OpenRouter models

credentials:
  openrouter_api_key: "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"

model_deployments:
  - name: openai/o3
    model_name: openai/o3
    tokenizer_name: openai/gpt-3.5-turbo
    max_sequence_length: 128000
    client_spec:
      class_name: "helm.clients.openrouter_client.OpenRouterClient"

  - name: anthropic/claude-sonnet-4
    model_name: anthropic/claude-sonnet-4
    tokenizer_name: anthropic/claude
    max_sequence_length: 200000
    client_spec:
      class_name: "helm.clients.openrouter_client.OpenRouterClient"

  - name: google/gemini-2.5-pro
    model_name: google/gemini-2.5-pro
    tokenizer_name: google/gemma-2b
    max_sequence_length: 1048576
    client_spec:
      class_name: "helm.clients.openrouter_client.OpenRouterClient"

  - name: meta-llama/llama-4-maverick
    model_name: meta-llama/llama-4-maverick
    tokenizer_name: meta-llama/llama-3-70b-instruct
    max_sequence_length: 1048576
    client_spec:
      class_name: "helm.clients.openrouter_client.OpenRouterClient"

  - name: mistralai/mistral-large
    model_name: mistralai/mistral-large
    tokenizer_name: mistralai/mistral-7b
    max_sequence_length: 32768
    client_spec:
      class_name: "helm.clients.openrouter_client.OpenRouterClient"

  - name: deepseek-ai/deepseek-v3
    model_name: deepseek-ai/deepseek-v3
    tokenizer_name: deepseek-ai/deepseek-coder-v1.5
    max_sequence_length: 1048576
    client_spec:
      class_name: "helm.clients.openrouter_client.OpenRouterClient"
